### ISSUE TITLE
broken after upgrade to Fedora 41 / python 3.13

### ISSUE THREAD

**Issue by antvrs** [pychess/pychess#2299]
Hello,
  As is now custom, pychess has become unusable after updating my system. 
  Fedora common install uses 1.0.3. Trying to start a FICS game will abort and disconnect upon the first move. 
  "AttributeError: 'ICSStreamReaderProtocol' object has no attribute '_stream_writer"
is the terminal error. 
 Is there a current fc41 1.0.5 rpm, some way to use this with python 3.13 or any sort of workaround?
  Thanks as always for keeping up with this. It remains for preferred FICS client.
  -A

**Comment by gbtami** [comment]
You can always use it from sources. Just git clone this repo, and if you already have all the dependencies installed you can run it like `./pychess`
(You have to run `./create_theme_preview.sh` and `./pgn2ecodb.sh` once to get some generated stuff not stored in git but existing in releases.)

p.s. I suggest to try lichess.org instead of FICS. It lightning years better than anything else :)

**Comment by antvrs** [comment]
Thanks for the suggestions. I find some use for lichess but prefer the pace of FICS and tournament play. 
 
attempting to play, I can log in, all functions work but then, when I make my first move, I get:
"The game has been killed Because the connection to the server was lost"
 
I have already been using pychess source as you suggest above but get the same issue. 
 ( running ./pgn2ecodb.sh gets  errors:
 .." pychess-master/lib/pychess/Database/PgnImport.py", line 445, in do_import
    self.conn.commit()
    ^^^^^^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute 'commit'  
")

**Comment by gbtami** [comment]
Seems pychess needs some love to handle newer versions of its dependencies :(

**Comment by antvrs** [comment]
the problem was already there in the previous fedora 40  in v1.0.3 but now is an issue for 1.0.5 from source code after upgrading.  
 Perhaps something with changes to telnet support? 
 _A

**Comment by gbtami** [comment]
I can play games on FICS with 1.0.5 on Ubuntu 24.04.
I suggest to start it like `pychess --log-debug --log-view` then open the log window with View -> Log viewer
where you can see the FICS communication and everything else.
![https://imgur.com/Fvz9WNG.png](https://imgur.com/Fvz9WNG.png)

**Comment by antvrs** [comment]
starting a game,  log shows:

08:54:16
------------------------------------------------------------
Executing <Task pending name='Task-79' coro=<GameModel.start.<locals>.coro() running at /usr/lib/python3.13/site-packages/pychess/Utils/GameModel.py:777> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib64/python3.13/asyncio/base_events.py:460> created at /usr/lib/python3.13/site-packages/pychess/compat.py:5> took 0.120 seconds
Fatal error: protocol.data_received() call failed.
handle_traceback: Handle created at (most recent call last):
  File "/usr/bin/pychess", line 255, in <module>
    loop.run_forever()
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 2019, in _run_once
    handle._run()
  File "/usr/lib64/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib64/python3.13/asyncio/selector_events.py", line 920, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "/usr/lib64/python3.13/asyncio/selector_events.py", line 276, in _add_reader
    handle = events.Handle(callback, args, self, None)
protocol: <pychess.ic.TimeSeal.ICSStreamReaderProtocol object at 0x7fa2eb5c4ec0>
transport: <_SelectorSocketTransport fd=22 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.13/asyncio/selector_events.py", line 1019, in _read_ready__data_received
    self._protocol.data_received(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/pychess/ic/TimeSeal.py", line 64, in data_received
    cooked = self.cook_some(data)
  File "/usr/lib/python3.13/site-packages/pychess/ic/TimeSeal.py", line 90, in cook_some
    self._stream_writer.write(self.encode(bytearray(G_RESPONSE, "utf-8")) + b"\n")
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ICSStreamReaderProtocol' object has no attribute '_stream_writer'. Did you mean: '_stream_reader'?

__
I will try posting in Fedora forums, to see if anyone else can repeat. 
_A

**Comment by AdamWill** [comment]
So I spent a bit of time poking at pychess for Fedora in the last day, but I'm giving up. I have some notes, though!

`AttributeError: 'Connection' object has no attribute 'commit'` happens if you have sqlalchemy 1.4 instead of 2.0. Remove all `python3-sqlalchemy1.4` packages and install the `python3-sqlalchemy` packages instead.

Every other problem I ran into seems to boil down to weird/old/wrong/bad usage of asyncio. Running the pychess test suite shows quite a lot of apparent problems with asyncio. It's worst on Fedora 43 with Python 3.14, where `asyncio.get_event_loop()` now raises a `RuntimeError` if there is no currently-running event loop, but the 1.0.5 test suite doesn't pass even on Fedora 42 with Python 3.13:
```
======================================================================
ERROR: test1 (analysis.CECPTests.test1)
Test analyzing in forced mate situations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/analysis.py", line 83, in setUp
    self.engineA, self.analyzerA = self._setupengine(ANALYZING)
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/analysis.py", line 60, in _setupengine
    analyzer = CECPEngine(engine, WHITE, 2, 0)
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/lib/pychess/Players/CECPEngine.py", line 174, in __init__
    self.parse_line_task = asyncio.create_task(self.parseLine(self.engine))
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test2 (analysis.CECPTests.test2)
Test analyzing in promotion situations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/analysis.py", line 83, in setUp
    self.engineA, self.analyzerA = self._setupengine(ANALYZING)
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/analysis.py", line 60, in _setupengine
    analyzer = CECPEngine(engine, WHITE, 2, 0)
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/lib/pychess/Players/CECPEngine.py", line 174, in __init__
    self.parse_line_task = asyncio.create_task(self.parseLine(self.engine))
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test0 (learn.LearnTests.test0)
Init layout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/learn.py", line 40, in setUp
    self.dd_task = asyncio.create_task(dd.start())
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test1 (learn.LearnTests.test1)
Start next endgame
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/learn.py", line 40, in setUp
    self.dd_task = asyncio.create_task(dd.start())
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test2 (learn.LearnTests.test2)
Start next lecture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/learn.py", line 40, in setUp
    self.dd_task = asyncio.create_task(dd.start())
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test3 (learn.LearnTests.test3)
Start next lesson
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/learn.py", line 40, in setUp
    self.dd_task = asyncio.create_task(dd.start())
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
======================================================================
ERROR: test4 (learn.LearnTests.test4)
Start next puzzle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/testing/learn.py", line 40, in setUp
    self.dd_task = asyncio.create_task(dd.start())
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.13/asyncio/tasks.py", line 407, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
----------------------------------------------------------------------
Ran 144 tests in 168.146s
FAILED (errors=7)
```
I tried various hacks just to the tests to use `asyncio.run` or create an event loop if we get a runtime error, but nothing really works. There seem to be more fundamental issues with how pychess uses asyncio that are just being exposed here.

It's a big complex app and the usage of asyncio is hard to figure out from scratch, so I'm gonna give up and propose dropping pychess from the Fedora games spin to get it to compose again, instead of trying any harder to fix it...

**Comment by AdamWill** [comment]
Building on Rawhide (with Python 3.14) has the same seven clearly identifiable errors, but this traceback is also shown multiple times in the output:
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.5-build/pychess-1.0.5/lib/pychess/ic/ICGameModel.py", line 363, in onKibitzMessage
    self.kibitz_task = asyncio.create_task(coro())
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.14/asyncio/tasks.py", line 394, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
```
you can see the full output [here](https://kojipkgs.fedoraproject.org/work/tasks/2584/135082584/build.log) (at least for a while, the task will get garbage-collected at some point).

**Comment by AdamWill** [comment]
As for the `AttributeError: 'ICSStreamReaderProtocol' object has no attribute '_stream_writer'.` problem, that is caused by https://github.com/python/cpython/commit/a355f60b032306651ca27bc53bbb82eb5106ff71 , which landed in 3.13. `ICSStreamReaderProtocol` inherits from `asyncio.StreamReaderProtocol`, and as of that commit, `asyncio.StreamReaderProtocol` no longer has a `_stream_writer` attribute.

**Comment by AdamWill** [comment]
ah, hmm, OK, so there's a couple of things going on. I can get 1.0.3 to pass tests on Python 3.14 with just this change:
```
diff --git a/testing/analysis.py b/testing/analysis.py
index 2c1841e1..602a986a 100755
--- a/testing/analysis.py
+++ b/testing/analysis.py
@@ -76,7 +76,11 @@ class CECPTests(EmittingTestCase):
         self.assertEqual(results, ([(ply, moves, score, depth, nps)], ))
 
     def setUp(self):
-        self.loop = asyncio.get_event_loop()
+        try:
+            self.loop = asyncio.get_event_loop()
+        except RuntimeError:
+            self.loop = asyncio.new_event_loop()
+            asyncio.set_event_loop(self.loop)
 
         self.engineA, self.analyzerA = self._setupengine(ANALYZING)
         self.engineI, self.analyzerI = self._setupengine(INVERSE_ANALYZING)
```
plus backporting the port from distutils to setuptools. the failures we're seeing with 1.0.5 are something introduced between 1.0.3 and 1.0.5, I think. I might be able to spend a bit of time bisecting down to exactly what triggered those.

**Comment by AdamWill** [comment]
I *think* this might fix the FICS problem:
```
--- a/lib/pychess/ic/TimeSeal.py
+++ b/lib/pychess/ic/TimeSeal.py
@@ -85,8 +85,9 @@ class ICSStreamReaderProtocol(asyncio.StreamReaderProtocol):
             log.debug(data, extra={"task": (self.name, "raw")})
 
             if self.timeseal:
+                writer = asyncio.StreamWriter(self._transport, self, self._stream_reader, self._loop)
                 for i in range(g_count):
-                    self._stream_writer.write(self.encode(bytearray(G_RESPONSE, "utf-8")) + b"\n")
+                    writer.write(self.encode(bytearray(G_RESPONSE, "utf-8")) + b"\n")
         return data
 
     def encode(self, inbuf, timestamp=None):
```
but I can't really test as I don't really play chess, don't have a FICS account, and don't want to annoy anyone by trying to sign up for one and figure out how to play a game, only to lose terribly or quit after a move...I don't know if there's a test mode to play against a bot or anything.

**EDIT**: found out how to test, it does not work :( it makes pychess hang on connection to the server, not sure why. Any ideas?

**Comment by AdamWill** [comment]
hmm, a note after more fiddling around: the event loop can actually get leaked across tests run in the same process. Running on 1.0.3 with my patched analysis.py:
```
PYTHONPATH=../lib PYCHESS_UNITTEST=true xvfb-run -a coverage run --source ../lib -m unittest polyglot.py
[ ... lots of warning spam ... ]
======================================================================
ERROR: testPolyglot_2 (polyglot.PolyglotTestCase.testPolyglot_2)
Testing Polyglot book creation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pychess-1.0.3-build/pychess-1.0.3/testing/polyglot.py", line 118, in testPolyglot_2
    loop = asyncio.get_event_loop()
  File "/usr/lib64/python3.14/asyncio/events.py", line 718, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

----------------------------------------------------------------------
Ran 2 tests in 0.131s

FAILED (errors=1)
```
but:
```
PYTHONPATH=../lib PYCHESS_UNITTEST=true xvfb-run -a coverage run --source ../lib -m unittest analysis.py polyglot.py
[ ... warning spam ...]
Ran 4 tests in 0.143s

OK
```
that is, running polyglot.py alone fails, but running it after analysis.py in the same run passes. Same result with learn.py - it fails run alone, passes run after the (fixed) analysis.py. So...tests that don't set up a loop at all, but run into asyncio code, are implicitly relying on some other test that sets up a loop running before them (e.g. `learn.py`, which doesn't set up a loop but does call `asyncio.create_task`). Up till Python 3.14, the first call to `asyncio.get_event_loop()` in *any* test was creating a loop that was then probably used by all the tests, but with 3.14, `asyncio.get_event_loop()` does not create a loop if there isn't one already. So fixing analysis.py fixed all the tests for Fedora's package build because we run the tests in alphabetical order...but a 'correct' fix would probably mean making a similar change to every other test that calls `get_event_loop()`, and adding similar code to any other tests like `learn.py` which run asyncio stuff but don't currently explicitly set up a loop...

**Comment by gbtami** [comment]
FICS usually has several bots online to play with.
Btw how did you landed here if you don't really play chess? :)

**Comment by gbtami** [comment]
Ahh, I see now. You committed that telnetlib fix before.
Thx for working on pychess issues again! The truth is I spent almost zero time in latest years on this project myself after I started to build a lichess-like chess variant server https://github.com/gbtami/pychess-variants
Thx to hartwork (who joined and helped releasing new versions) this software is still alive.

**Comment by AdamWill** [comment]
I'm a Fedora QA team member, I try and fix broken Fedora stuff :P I came across this because I was looking at failed image composes, and our games image is failing to compose because it wants to include pychess, but the Fedora pychess package isn't installable since Rawhide went to Python 3.14, because we can't rebuild it against Python 3.14.

**Comment by AdamWill** [comment]
I just did a bisect, and it looks like the failures we're getting with 1.0.5 bisect to 983e138e , "compat.py is not needed from python3.7". That dropped a wrapper around task creation...

I do wonder if the tests would pass for us if we ran them in the same order in which run_tests.py runs them...I might try that...

**Comment by AdamWill** [comment]
Hah. So, I sent a [test PR that bumps the tested Python version to 3.13](https://github.com/pychess/pychess/pull/2359). Two things I learned from that:

1. The tests do fail the same way I'm seeing in Fedora package builds
2. The GHA workflow is broken, so you don't notice that the tests failed unless you go look at [the logs](https://productionresultssa2.blob.core.windows.net/actions-results/b95c2b16-b3f2-4d7c-acd2-564daa24dc5f/workflow-job-run-a4c8fe2b-c53c-55de-8e4f-9d0879b33470/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-07-21T22%3A11%3A19Z&sig=lRWJg2bgNKpIyrrkoSNDo7Sdk4vHuFYtGjX6CtGWT1Q%3D&ske=2025-07-22T08%3A08%3A19Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-07-21T20%3A08%3A19Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-07-21T22%3A01%3A14Z&sv=2025-05-05)

I think the problem with the workflow is that the "Run the test suite (with virtual X11 server)" step has `kill -s SIGTERM "${xvfb_pid}"` after `./run3 run_tests.py`, so the exit code of the `kill` command determines whether the step 'passed' or 'failed', not the exit code of the test run command...

edit: well, it's more broken than that - `run_tests.py` will never exit anything other than 0 as it stands...

**Comment by AdamWill** [comment]
Hah. In fact, the tests are failing even on 3.12, but because your github workflow is broken, you never noticed. Check e.g. https://github.com/pychess/pychess/pull/2357 - all the tests "passed", but if you go look at the raw logs for the Python 3.12 test suite execution - https://productionresultssa16.blob.core.windows.net/actions-results/42bfa934-ea15-4b81-bb4f-a39428539404/workflow-job-run-130d4d3b-862d-51dc-8bf4-7ebf1dc1fc92/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-07-21T22%3A24%3A55Z&sig=3Cgcou9C0M5ECqYJg5T54k38QUgB1FT1eDbskbAy2IU%3D&ske=2025-07-22T08%3A08%3A31Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-07-21T20%3A08%3A31Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-07-21T22%3A14%3A50Z&sv=2025-05-05 - it has the same failures:
```
2025-07-07T15:19:05.4373592Z ======================================================================
2025-07-07T15:19:05.4376494Z ERROR: test1 (analysis.CECPTests.test1)
2025-07-07T15:19:05.4379556Z Test analyzing in forced mate situations
2025-07-07T15:19:05.4380982Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4382686Z Traceback (most recent call last):
2025-07-07T15:19:05.4383442Z   File "/home/runner/work/pychess/pychess/testing/analysis.py", line 83, in setUp
2025-07-07T15:19:05.4384540Z     self.engineA, self.analyzerA = self._setupengine(ANALYZING)
2025-07-07T15:19:05.4385228Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4386028Z   File "/home/runner/work/pychess/pychess/testing/analysis.py", line 60, in _setupengine
2025-07-07T15:19:05.4386899Z     analyzer = CECPEngine(engine, WHITE, 2, 0)
2025-07-07T15:19:05.4388266Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4391520Z   File "/home/runner/work/pychess/pychess/lib/pychess/Players/CECPEngine.py", line 174, in __init__
2025-07-07T15:19:05.4392436Z     self.parse_line_task = asyncio.create_task(self.parseLine(self.engine))
2025-07-07T15:19:05.4393006Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4393767Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4394459Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4394822Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4395154Z RuntimeError: no running event loop
2025-07-07T15:19:05.4395388Z 
2025-07-07T15:19:05.4395511Z ======================================================================
2025-07-07T15:19:05.4395918Z ERROR: test2 (analysis.CECPTests.test2)
2025-07-07T15:19:05.4396298Z Test analyzing in promotion situations
2025-07-07T15:19:05.4396713Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4397448Z Traceback (most recent call last):
2025-07-07T15:19:05.4398062Z   File "/home/runner/work/pychess/pychess/testing/analysis.py", line 83, in setUp
2025-07-07T15:19:05.4398736Z     self.engineA, self.analyzerA = self._setupengine(ANALYZING)
2025-07-07T15:19:05.4399470Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4400124Z   File "/home/runner/work/pychess/pychess/testing/analysis.py", line 60, in _setupengine
2025-07-07T15:19:05.4400782Z     analyzer = CECPEngine(engine, WHITE, 2, 0)
2025-07-07T15:19:05.4401172Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4401863Z   File "/home/runner/work/pychess/pychess/lib/pychess/Players/CECPEngine.py", line 174, in __init__
2025-07-07T15:19:05.4402732Z     self.parse_line_task = asyncio.create_task(self.parseLine(self.engine))
2025-07-07T15:19:05.4403268Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4404008Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4404720Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4405065Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4405403Z RuntimeError: no running event loop
2025-07-07T15:19:05.4405645Z 
2025-07-07T15:19:05.4406031Z ======================================================================
2025-07-07T15:19:05.4406433Z ERROR: test0 (learn.LearnTests.test0)
2025-07-07T15:19:05.4406770Z Init layout
2025-07-07T15:19:05.4407072Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4407508Z Traceback (most recent call last):
2025-07-07T15:19:05.4408071Z   File "/home/runner/work/pychess/pychess/testing/learn.py", line 40, in setUp
2025-07-07T15:19:05.4408666Z     self.dd_task = asyncio.create_task(dd.start())
2025-07-07T15:19:05.4409245Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4409942Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4410640Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4410963Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4411293Z RuntimeError: no running event loop
2025-07-07T15:19:05.4411527Z 
2025-07-07T15:19:05.4411675Z ======================================================================
2025-07-07T15:19:05.4412059Z ERROR: test1 (learn.LearnTests.test1)
2025-07-07T15:19:05.4412417Z Start next endgame
2025-07-07T15:19:05.4412734Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4413155Z Traceback (most recent call last):
2025-07-07T15:19:05.4413702Z   File "/home/runner/work/pychess/pychess/testing/learn.py", line 40, in setUp
2025-07-07T15:19:05.4414275Z     self.dd_task = asyncio.create_task(dd.start())
2025-07-07T15:19:05.4414659Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4415315Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4415965Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4416282Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4416604Z RuntimeError: no running event loop
2025-07-07T15:19:05.4416845Z 
2025-07-07T15:19:05.4416982Z ======================================================================
2025-07-07T15:19:05.4417359Z ERROR: test2 (learn.LearnTests.test2)
2025-07-07T15:19:05.4417694Z Start next lecture
2025-07-07T15:19:05.4418010Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4418423Z Traceback (most recent call last):
2025-07-07T15:19:05.4419140Z   File "/home/runner/work/pychess/pychess/testing/learn.py", line 40, in setUp
2025-07-07T15:19:05.4419714Z     self.dd_task = asyncio.create_task(dd.start())
2025-07-07T15:19:05.4420088Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4420747Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4421633Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4421955Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4422272Z RuntimeError: no running event loop
2025-07-07T15:19:05.4422492Z 
2025-07-07T15:19:05.4422619Z ======================================================================
2025-07-07T15:19:05.4422996Z ERROR: test3 (learn.LearnTests.test3)
2025-07-07T15:19:05.4424756Z Start next lesson
2025-07-07T15:19:05.4425196Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4426411Z Traceback (most recent call last):
2025-07-07T15:19:05.4426994Z   File "/home/runner/work/pychess/pychess/testing/learn.py", line 40, in setUp
2025-07-07T15:19:05.4427568Z     self.dd_task = asyncio.create_task(dd.start())
2025-07-07T15:19:05.4427947Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4428622Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4429497Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4429827Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4430143Z RuntimeError: no running event loop
2025-07-07T15:19:05.4430366Z 
2025-07-07T15:19:05.4430743Z ======================================================================
2025-07-07T15:19:05.4431139Z ERROR: test4 (learn.LearnTests.test4)
2025-07-07T15:19:05.4431496Z Start next puzzle
2025-07-07T15:19:05.4439347Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4439800Z Traceback (most recent call last):
2025-07-07T15:19:05.4440378Z   File "/home/runner/work/pychess/pychess/testing/learn.py", line 40, in setUp
2025-07-07T15:19:05.4440968Z     self.dd_task = asyncio.create_task(dd.start())
2025-07-07T15:19:05.4441373Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4442076Z   File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/tasks.py", line 417, in create_task
2025-07-07T15:19:05.4442774Z     loop = events.get_running_loop()
2025-07-07T15:19:05.4443126Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-07T15:19:05.4443478Z RuntimeError: no running event loop
2025-07-07T15:19:05.4443722Z 
2025-07-07T15:19:05.4443901Z ----------------------------------------------------------------------
2025-07-07T15:19:05.4444330Z Ran 138 tests in 122.619s
2025-07-07T15:19:05.4444517Z 
2025-07-07T15:19:05.4444612Z FAILED (errors=7)
```
I suspect this has maybe been broken ever since https://github.com/pychess/pychess/commit/983e138e29f890002ef439d361f767182d7c70fa landed and nobody noticed?

**Comment by AdamWill** [comment]
> FICS usually has several bots online to play with.

Thanks, I found out how to identify them - (C) in the name. So I was able to test my attempted fix for the stream writer issue. Unfortunately it doesn't work :( It causes pychess to hang and become unresponsive during connection to the server. I'm not sure why.

**Comment by antvrs** [comment]
Thanks for taking this up and supporting Fedora in general, Adam.  I respect that gbtami has moved on to lichess but FICS is still active enough to keep me there. 
(www.teamleague.org still holds long game tournaments on FICS, one currently.)  I use a java client for now, www.pearlchess.com, which gets the job done but do miss many features and the appearance of pychess. 
  Will follow along here and test anything that emerges. Thanks again. -A

**Comment by gbtami** [comment]
Fix committed. 
@AdamWill @antvrs can you test it if you have some time, please?

**Comment by antvrs** [comment]
Sorry, still the same problem. 
 executing ./pychess from the latest zip gets the same issue, 
" AttributeError: 'ICSStreamReader' object has no attribute 'writer' "

**Comment by AdamWill** [comment]
that sounds like you didn't actually get the fix - if you did, at least the error message should be slightly different.

**Comment by AdamWill** [comment]
I did a scratch build of 1.0.5 with the other fixes plus this one, for Fedora 42, at https://koji.fedoraproject.org/koji/taskinfo?taskID=135153953 - can you test that?

**Comment by AdamWill** [comment]
oh, no, I see the same:
```
  File "/usr/lib/python3.14/site-packages/pychess/ic/TimeSeal.py", line 67, in data_received
    cooked = self.cook_some(data)
  File "/usr/lib/python3.14/site-packages/pychess/ic/TimeSeal.py", line 93, in cook_some
    self._stream_reader.writer.write(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ICSStreamReader' object has no attribute 'writer'
```
so yeah, the fix doesn't quite work. Let me see if I can see what's wrong with it.

**Comment by AdamWill** [comment]
yeah, no, the fix is just broken AFAICT. `ICSStreamReader` inherits from `asyncio.StreamReader` and neither of those have a `writer` property. `asyncio.StreamReader` does have a `_w*a*iter` property (emphasis added) - maybe @gbtami misread?

**Comment by gbtami** [comment]
@AdamWill ok I'm stupid :) Fixed my fix now. Retry please.

**Comment by antvrs** [comment]
Working for me now, great!
