### ISSUE TITLE
Analyser arrows are gone

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1027]
I can't see the green and red arrows any more, and I get a lot of these in the console instead

```
Traceback (most recent call last):
  File "/opt/pychess/lib/pychess/widgets/gamewidget.py", line 428, in _on_analyze
    self._set_arrow(analyzer_type, moves[0].cords)
  File "/opt/pychess/lib/pychess/widgets/gamewidget.py", line 394, in _set_arrow
    self.board.view._set_greenarrow(coordinates)
  File "/opt/pychess/lib/pychess/widgets/BoardView.py", line 1307, in _set_greenarrow
    r = Gdk.rectangle_union(r, rect(self.cord2RectRelative(cord)))
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'rectangle_union'
```

**Comment by gbtami** [comment]
Seems this is a gobject-introspection bug, see:
https://bugzilla.redhat.com/show_bug.cgi?id=1269901
https://github.com/mypaint/mypaint/issues/433
https://github.com/mypaint/mypaint/issues/437

Anyhow, I'v committed a fix creating our own union().

**Comment by massimiliano-leoni** [comment]
Good, but you might want to revert this commit when the bug is fixed upstream.

**Comment by gbtami** [comment]
Agreed.
